name: "Self-test"

on:
  push:
    branches:
      - main
  pull_request:

env:
  KUBECONFIG: ${{ github.workspace }}/__kubeconfig_tmp__

jobs:
  self-test:
    name: Self-test
    runs-on: ubuntu-latest
    steps:

      # This isn't needed to perform a deployment, but is required to do the
      # local self-test (for `uses: ./`)
      - name: Check out code
        uses: actions/checkout@v2

      - name: Authenticate to cluster
        run: echo ${{ secrets.LINODE_KUBECONFIG }} | base64 -d > $KUBECONFIG

      - name: Check cluster info
        run: kubectl cluster-info dump

      - name: Run this action
        uses: ./
        with:
          namespace: github-actions
          deployment: www
          container: nginx
          image: nginx:latest
          token: ${{ secrets.GITHUB_TOKEN }}
          transient: ${{ github.event_name == 'pull_request' }}
          production: ${{ github.event_name == 'push' }}
          url: https://example.com/${{ github.ref }}
          environment: ${{ github.event_name == 'push' && 'production' || format('dev-{0}', github.ref) }}
