name: "Self-test"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build docker images
    runs-on: ubuntu-latest
    steps:


      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@master
        with:
          # export_default_credentials: true
          project_id: ${{ secrets.GKE_PROJECT }}
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@main
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
          location: ${{ secrets.GKE_CLUSTER_LOCATION }}

      - name: Run this action
        uses: ./
        with:
          namespace: github-actions
          deployment: www
          container: nginx
          image: nginx:latest
          token: ${{ secrets.GITHUB_TOKEN }}
