name: "Self-test"

on:
  push:
    branches:
      - main
  pull_request:
    # All PRs
  deployment:

jobs:
  self-test:
    name: Self-test
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@main
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
          location: ${{ secrets.GKE_CLUSTER_LOCATION }}
          credentials: ${{ secrets.GCP_SA_KEY }}

      - name: Run this action
        uses: ./
        with:
          namespace: github-actions
          deployment: www
          container: nginx
          image: nginx:latest
          token: ${{ secrets.GITHUB_TOKEN }}
          transient: ${{ github.event_name == 'pull_request' }}
          production: ${{ github.event_name == 'push' }}
          url: https://example.com/${{ github.ref }}
          environment: ${{ github.event_name == 'push' && 'production' || format('dev-{0}', github.ref) }}
