name: "Self-test"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  self-test:
    name: Self-test
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v2


#       - name: Setup gcloud CLI
#         uses: google-github-actions/setup-gcloud@master
#         with:
#           export_default_credentials: true
#           project_id: ${{ secrets.GKE_PROJECT }}
#           service_account_email: ${{ secrets.GCP_SA_EMAIL }}
#           service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@main
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER_NAME }}
          location: ${{ secrets.GKE_CLUSTER_LOCATION }}
          credentials: ${{ secrets.GCP_SA_KEY }}

      - name: Run this action
        uses: ./
        with:
          namespace: github-actions
          deployment: www
          container: nginx
          image: nginx:latest
          token: ${{ secrets.GITHUB_TOKEN }}
